language: node_js

node_js:
    - "node"
    - "9"
    - "8"
    - "7"

sudo: false

git:
    submodules: false

before_script:
    - npm install

script:
    - npm test

after_success:
    - npm run report-coverage
    - npm run test-scrutinizer
