language: node_js

node_js:
    - "node"
    - "9"
    - "8"
    - "7"

sudo: required

services: 
  - docker

git:
    submodules: false

before_script:
    - npm install

script:
    - npm test

after_success:
    - npm run report-coverage
    - npm run test-scrutinizer
    - npm run docker_latest
    - npm run docker_8
    - npm run docker_7
