language: node_js

node_js:
    - "node"
    - "9"
    - "8"
    - "7"

sudo: required

services: 
  - docker

git:
    submodules: false

before_script:
    - npm install

script:
    - npm run travis
    
after_success:
    - npm run report-coverage
    - npm run docker-latest
    - npm run docker-8
    - npm run docker-7
