version: "3"
services:
  express:
    image: "node:alpine"
    working_dir: /app
    environment:
        - DBWEBB_DSN=mongodb://mongodb:27017/mumin
    volumes:
        - ./:/app/
    ports:
        - 3000:3000
    links:
        - mongodb
    command: "npm start"

  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
        - MONGO_DATA_DIR=/data/db
    volumes:
        - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod

  node_latest:
    build:
      context: .
      dockerfile: docker/Dockerfile-node-latest
    volumes:
      - ./:/app/
    ports:
      - "3001:3000"
    command: "npm test"

  node_8:
    build:
      context: .
      dockerfile: docker/Dockerfile-node-8
    volumes:
      - ./:/app/
    ports:
      - "3002:3000"
    command: "npm test"

  node_6:
    build:
      context: .
      dockerfile: docker/Dockerfile-node-6
    volumes:
      - ./:/app/
    ports:
      - "3003:3000"
    command: "npm test"

  