version: "2"
services:
  node_latest:
    image: "node:9.0.0"
    working_dir: /app
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"

  node_8:
    image: "node:8.9.0"
    working_dir: /app
    volumes:
      - ./:/app/
    ports:
      - "3001:3000"

  node_6:
    image: "node:6.11.5"
    working_dir: /app
    volumes:
      - ./:/app/
    ports:
      - "3002:3000"
